// community/templates/sveltekit-starter/src/components/tambo/Message.svelte
<script lang="ts">
  import { cn } from "$lib/utils.js";
  import MessageContent from "./MessageContent.svelte";
  import { ChevronDown, Check, Loader2, X } from "lucide-svelte";
  import type { TamboThreadMessage, ContentPart } from "$lib/tambo/types.js";
  import { getTamboContext } from "$lib/tambo/context.js";
  import type { Snippet } from "svelte";

  type ToolCallRequest = NonNullable<TamboThreadMessage["toolCallRequest"]>;

  interface Props {
    role: "user" | "assistant";
    message: TamboThreadMessage;
    variant?: "default" | "solid";
    isLoading?: boolean;
    class?: string;
    children?: Snippet;
  }

  let {
    role,
    message,
    variant = "default",
    isLoading = false,
    class: className,
    children,
  }: Props = $props();

  // Don't render tool messages directly
  const shouldRender = $derived(message.role !== "tool");

  // Tool call state
  let toolExpanded = $state(false);

  /**
   * Get tool call request from message
   */
  function getToolCallRequest(): ToolCallRequest | undefined {
    return message.toolCallRequest ?? message.component?.toolCallRequest;
  }

  /**
   * Get images from message content
   */
  function getMessageImages(
    content: string | ContentPart[] | null | undefined
  ): string[] {
    if (!content || !Array.isArray(content)) return [];
    return content
      .filter((item) => item?.type === "image_url" && item.image_url?.url)
      .map((item) => (item as { type: "image_url"; image_url: { url: string } }).image_url.url);
  }

  const images = $derived(getMessageImages(message.content));
  const hasToolCall = $derived(!!getToolCallRequest());
  const toolCallRequest = $derived(getToolCallRequest());

  // Get component from registry if rendered
  const tambo = getTamboContext();

  const registeredComponent = $derived(
    message.component?.name ? tambo.thread.getComponent(message.component.name) : undefined
  );

  /**
   * Format tool parameters for display
   */
  function formatParameters(
    params: ToolCallRequest["parameters"]
  ): Record<string, unknown> {
    if (!params) return {};
    return Object.fromEntries(params.map((p) => [p.parameterName, p.parameterValue]));
  }
</script>

{#if shouldRender}
  <div
    class={cn(
      "flex",
      variant === "solid" &&
        "[&>div>div:first-child]:shadow-md [&>div>div:first-child]:bg-container/50",
      className
    )}
    data-message-role={role}
    data-message-id={message.id}
  >
    {#if children}
      {@render children()}
    {:else}
      <div class={cn("flex flex-col", role === "assistant" ? "w-full" : "max-w-3xl")}>
        <!-- Reasoning info (for models with extended thinking) -->
        {#if message.reasoning && message.reasoning.length > 0}
          <div class="flex flex-col items-start text-xs opacity-50 mb-2">
            <button
              type="button"
              class="flex items-center gap-1 cursor-pointer hover:bg-muted-foreground/10 rounded-md px-3 py-1"
              onclick={() => (toolExpanded = !toolExpanded)}
            >
              <span class={isLoading ? "animate-thinking-gradient" : ""}>
                {isLoading ? "Thinking..." : "Done Thinking"}
                {message.reasoning.length > 1 ? `(${message.reasoning.length} steps)` : ""}
              </span>
              <ChevronDown
                class={cn("w-3 h-3 transition-transform duration-200", !toolExpanded && "-rotate-90")}
              />
            </button>
            {#if toolExpanded}
              <div class="flex flex-col gap-1 px-3 py-3 max-h-96 overflow-auto">
                {#each message.reasoning as step, index}
                  <div class="flex flex-col gap-1">
                    {#if message.reasoning.length > 1}
                      <span class="text-muted-foreground text-xs font-medium">Step {index + 1}:</span>
                    {/if}
                    <div class="bg-muted/50 rounded-md p-3 text-xs whitespace-pre-wrap">
                      {step}
                    </div>
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        {/if}

        <!-- Images -->
        {#if images.length > 0}
          <div class="flex flex-wrap gap-2 mb-2">
            {#each images as imageUrl, index}
              <div class="w-32 h-32 rounded-md overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                <img
                  src={imageUrl}
                  alt={`Image ${index + 1}`}
                  class="w-full h-full object-cover"
                />
              </div>
            {/each}
          </div>
        {/if}

        <!-- Message content -->
        <MessageContent
          content={message.content}
          {isLoading}
          class={role === "assistant"
            ? "text-foreground font-sans"
            : "text-foreground bg-container hover:bg-backdrop font-sans"}
        />

        <!-- Tool call info -->
        {#if hasToolCall && role === "assistant"}
          <div class="flex flex-col items-start text-xs opacity-50 mt-2">
            <button
              type="button"
              class="flex items-center gap-1 cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 rounded-md p-1"
              onclick={() => (toolExpanded = !toolExpanded)}
            >
              {#if message.error}
                <X class="w-3 h-3 text-red-500" />
              {:else if isLoading}
                <Loader2 class="w-3 h-3 animate-spin" />
              {:else}
                <Check class="w-3 h-3 text-green-500" />
              {/if}
              <span>
                {isLoading ? "Calling" : "Called"} {toolCallRequest?.toolName ?? "tool"}
              </span>
              <ChevronDown
                class={cn("w-3 h-3 transition-transform duration-200", !toolExpanded && "-rotate-90")}
              />
            </button>
            {#if toolExpanded && toolCallRequest}
              <div class="flex flex-col gap-1 p-3 pl-7 overflow-auto">
                <span class="whitespace-pre-wrap pl-2">tool: {toolCallRequest.toolName}</span>
                <span class="whitespace-pre-wrap pl-2">
                  parameters: {JSON.stringify(formatParameters(toolCallRequest.parameters), null, 2)}
                </span>
              </div>
            {/if}
          </div>
        {/if}

        <!-- Rendered component -->
        {#if message.component && registeredComponent && role === "assistant" && !message.isCancelled}
          {@const DynamicComponent = registeredComponent.component}
          <div class="w-full pt-2 px-2">
            <DynamicComponent
              {...message.component.props}
            />
          </div>
        {/if}

        <!-- Cancelled indicator -->
        {#if message.isCancelled}
          <span class="text-muted-foreground text-xs px-4">cancelled</span>
        {/if}
      </div>
    {/if}
  </div>
{/if}

// cli/src/registry/message/message.tsx
"use client";

import { createMarkdownComponents } from "@/components/ui/markdown-components";
import { cn } from "@/lib/utils";
import type { TamboThreadMessage } from "@tambo-ai/react";
import { useTambo } from "@tambo-ai/react";
import type TamboAI from "@tambo-ai/typescript-sdk";
import { cva, type VariantProps } from "class-variance-authority";
import stringify from "json-stringify-pretty-compact";
import { Check, ChevronDown, ExternalLink, Loader2, X } from "lucide-react";
import Image from "next/image";
import * as React from "react";
import { useState } from "react";
import { Streamdown } from "streamdown";
import {
  checkHasContent,
  getMessageImages,
  getSafeContent,
} from "../lib/thread-hooks";

/**
 * CSS variants for the message container
 * @typedef {Object} MessageVariants
 * @property {string} default - Default styling
 * @property {string} solid - Solid styling with shadow effects
 */
const messageVariants = cva("flex", {
  variants: {
    variant: {
      default: "",
      solid: [
        "[&>div>div:first-child]:shadow-md",
        "[&>div>div:first-child]:bg-container/50",
        "[&>div>div:first-child]:hover:bg-container",
        "[&>div>div:first-child]:transition-all",
        "[&>div>div:first-child]:duration-200",
      ].join(" "),
    },
  },
  defaultVariants: {
    variant: "default",
  },
});

/**
 * @typedef MessageContextValue
 * @property {"user" | "assistant"} role - The role of the message sender.
 * @property {VariantProps<typeof messageVariants>["variant"]} [variant] - Optional styling variant for the message container.
 * @property {TamboThreadMessage} message - The full Tambo thread message object.
 * @property {boolean} [isLoading] - Optional flag to indicate if the message is in a loading state.
 */
interface MessageContextValue {
  role: "user" | "assistant";
  variant?: VariantProps<typeof messageVariants>["variant"];
  message: TamboThreadMessage;
  isLoading?: boolean;
}

/**
 * React Context for sharing message data and settings among sub-components.
 * @internal
 */
const MessageContext = React.createContext<MessageContextValue | null>(null);

/**
 * Hook to access the message context.
 * Throws an error if used outside of a Message component.
 * @returns {MessageContextValue} The message context value.
 * @throws {Error} If used outside of Message.
 * @internal
 */
const useMessageContext = () => {
  const context = React.useContext(MessageContext);
  if (!context) {
    throw new Error("Message sub-components must be used within a Message");
  }
  return context;
};

// --- Sub-Components ---

/**
 * Props for the Message component.
 * Extends standard HTMLDivElement attributes.
 */
export interface MessageProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, "content"> {
  /** The role of the message sender ('user' or 'assistant'). */
  role: "user" | "assistant";
  /** The full Tambo thread message object. */
  message: TamboThreadMessage;
  /** Optional styling variant for the message container. */
  variant?: VariantProps<typeof messageVariants>["variant"];
  /** Optional flag to indicate if the message is in a loading state. */
  isLoading?: boolean;
  /** The child elements to render within the root container. Typically includes Message.Bubble and Message.RenderedComponentArea. */
  children: React.ReactNode;
}

/**
 * The root container for a message component.
 * It establishes the context for its children and applies alignment styles based on the role.
 * @component Message
 * @example
 * ```tsx
 * <Message role="user" message={messageData} variant="solid">
 *   <Message.Bubble />
 *   <Message.RenderedComponentArea />
 * </Message>
 * ```
 */
const Message = React.forwardRef<HTMLDivElement, MessageProps>(
  (
    { children, className, role, variant, isLoading, message, ...props },
    ref,
  ) => {
    const contextValue = React.useMemo(
      () => ({ role, variant, isLoading, message }),
      [role, variant, isLoading, message],
    );

    // Don't render tool response messages as they're shown in tool call dropdowns
    if (message.actionType === "tool_response") {
      return null;
    }

    return (
      <MessageContext.Provider value={contextValue}>
        <div
          ref={ref}
          className={cn(messageVariants({ variant }), className)}
          data-message-role={role}
          data-message-id={message.id}
          {...props}
        >
          {children}
        </div>
      </MessageContext.Provider>
    );
  },
);
Message.displayName = "Message";

/**
 * Loading indicator with bouncing dots animation
 *
 * A reusable component that displays three animated dots for loading states.
 * Used in message content and tool status areas.
 *
 * @component
 * @param {React.HTMLAttributes<HTMLDivElement>} props - Standard HTML div props
 * @param {string} [props.className] - Optional CSS classes to apply
 * @returns {JSX.Element} Animated loading indicator component
 */
const LoadingIndicator: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({
  className,
  ...props
}) => {
  return (
    <div className={cn("flex items-center gap-1", className)} {...props}>
      <span className="w-1 h-1 bg-current rounded-full animate-bounce [animation-delay:-0.3s]"></span>
      <span className="w-1 h-1 bg-current rounded-full animate-bounce [animation-delay:-0.2s]"></span>
      <span className="w-1 h-1 bg-current rounded-full animate-bounce [animation-delay:-0.1s]"></span>
    </div>
  );
};
LoadingIndicator.displayName = "LoadingIndicator";

/**
 * Props for the MessageImages component.
 */
export type MessageImagesProps = React.HTMLAttributes<HTMLDivElement>;

/**
 * Displays images from message content horizontally.
 * @component MessageImages
 */
const MessageImages = React.forwardRef<HTMLDivElement, MessageImagesProps>(
  ({ className, ...props }, ref) => {
    const { message } = useMessageContext();
    const images = getMessageImages(message.content);

    if (images.length === 0) {
      return null;
    }

    return (
      <div
        ref={ref}
        className={cn("flex flex-wrap gap-2 mb-2", className)}
        data-slot="message-images"
        {...props}
      >
        {images.map((imageUrl: string, index: number) => (
          <div
            key={index}
            className="w-32 h-32 rounded-md overflow-hidden shadow-sm hover:shadow-md transition-shadow duration-200"
          >
            <Image
              src={imageUrl}
              alt={`Image ${index + 1}`}
              width={128}
              height={128}
              className="w-full h-full object-cover"
              unoptimized
            />
          </div>
        ))}
      </div>
    );
  },
);
MessageImages.displayName = "MessageImages";

/**
 * Props for the MessageContent component.
 * Extends standard HTMLDivElement attributes.
 */
export interface MessageContentProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, "content"> {
  /** Optional override for the message content. If not provided, uses the content from the message object in the context. */
  content?: string | { type: string; text?: string }[];
  /** Optional flag to render as Markdown. Default is true. */
  markdown?: boolean;
}

/**
 * Displays the message content with optional markdown formatting.
 * Only shows text content - tool calls are handled by ToolcallInfo component.
 * @component MessageContent
 */
const MessageContent = React.forwardRef<HTMLDivElement, MessageContentProps>(
  (
    { className, children, content: contentProp, markdown = true, ...props },
    ref,
  ) => {
    const { message, isLoading } = useMessageContext();
    const contentToRender = children ?? contentProp ?? message.content;

    const safeContent = React.useMemo(
      () => getSafeContent(contentToRender as TamboThreadMessage["content"]),
      [contentToRender],
    );
    const hasContent = React.useMemo(
      () => checkHasContent(contentToRender as TamboThreadMessage["content"]),
      [contentToRender],
    );

    const showLoading = isLoading && !hasContent;

    return (
      <div
        ref={ref}
        className={cn(
          "relative block rounded-3xl px-4 py-2 text-[15px] leading-relaxed transition-all duration-200 font-medium max-w-full [&_p]:py-1 [&_li]:list-item",
          className,
        )}
        data-slot="message-content"
        {...props}
      >
        {showLoading ? (
          <div
            className="flex items-center justify-start h-4 py-1"
            data-slot="message-loading-indicator"
          >
            <LoadingIndicator />
          </div>
        ) : (
          <div
            className={cn("break-words", !markdown && "whitespace-pre-wrap")}
            data-slot="message-content-text"
          >
            {!contentToRender ? (
              <span className="text-muted-foreground italic">
                Empty message
              </span>
            ) : React.isValidElement(contentToRender) ? (
              contentToRender
            ) : markdown ? (
              <Streamdown
                components={
                  createMarkdownComponents() as Record<
                    string,
                    React.ComponentType<Record<string, unknown>>
                  >
                }
              >
                {typeof safeContent === "string" ? safeContent : ""}
              </Streamdown>
            ) : (
              safeContent
            )}
            {message.isCancelled && (
              <span className="text-muted-foreground text-xs">cancelled</span>
            )}
          </div>
        )}
      </div>
    );
  },
);
MessageContent.displayName = "MessageContent";

/**
 * Props for the ToolcallInfo component.
 * Extends standard HTMLDivElement attributes.
 */
export interface ToolcallInfoProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, "content"> {
  /** Optional flag to render response content as Markdown. Default is true. */
  markdown?: boolean;
}

function getToolStatusMessage(
  message: TamboThreadMessage,
  isLoading: boolean | undefined,
) {
  const isToolCall = message.actionType === "tool_call";
  if (!isToolCall) return null;

  const toolCallMessage = isLoading
    ? `Calling ${message.toolCallRequest?.toolName ?? "tool"}`
    : `Called ${message.toolCallRequest?.toolName ?? "tool"}`;
  const toolStatusMessage = isLoading
    ? message.component?.statusMessage
    : message.component?.completionStatusMessage;
  return toolStatusMessage ?? toolCallMessage;
}

/**
 * Displays tool call information in a collapsible dropdown.
 * Shows tool name, parameters, and associated tool response.
 * @component ToolcallInfo
 */
const ToolcallInfo = React.forwardRef<HTMLDivElement, ToolcallInfoProps>(
  ({ className, markdown: _markdown = true, ...props }, ref) => {
    const [isExpanded, setIsExpanded] = useState(false);
    const { message, isLoading } = useMessageContext();
    const { thread } = useTambo();
    const toolDetailsId = React.useId();

    const associatedToolResponse = React.useMemo(() => {
      if (!thread?.messages) return null;
      const currentMessageIndex = thread.messages.findIndex(
        (m: TamboThreadMessage) => m.id === message.id,
      );
      if (currentMessageIndex === -1) return null;
      for (let i = currentMessageIndex + 1; i < thread.messages.length; i++) {
        const nextMessage = thread.messages[i];
        if (nextMessage.actionType === "tool_response") {
          return nextMessage;
        }
        if (nextMessage.actionType === "tool_call") {
          break;
        }
      }
      return null;
    }, [message, thread?.messages]);

    if (message.actionType !== "tool_call") {
      return null;
    }

    const toolCallRequest: TamboAI.ToolCallRequest | undefined =
      message.toolCallRequest ?? message.component?.toolCallRequest;
    const hasToolError = message.error;

    const toolStatusMessage = getToolStatusMessage(message, isLoading);

    return (
      <div
        ref={ref}
        className={cn(
          "flex flex-col items-start text-xs opacity-50 pt-2",
          className,
        )}
        data-slot="toolcall-info"
        {...props}
      >
        <div className="flex flex-col gap-2">
          <button
            type="button"
            aria-expanded={isExpanded}
            aria-controls={toolDetailsId}
            onClick={() => setIsExpanded(!isExpanded)}
            className={cn(
              "flex items-center gap-1 cursor-pointer hover:bg-gray-100 rounded-md p-1 select-none w-fit",
            )}
          >
            {hasToolError ? (
              <X className="w-3 h-3 text-bold text-red-500" />
            ) : isLoading ? (
              <Loader2 className="w-3 h-3 text-muted-foreground text-bold animate-spin" />
            ) : (
              <Check className="w-3 h-3 text-bold text-green-500" />
            )}
            <span>{toolStatusMessage}</span>
            <ChevronDown
              className={cn(
                "w-3 h-3 transition-transform duration-200",
                !isExpanded && "-rotate-90",
              )}
            />
          </button>
          <div
            id={toolDetailsId}
            className={cn(
              "flex flex-col gap-1 p-3 overflow-auto transition-[max-height,opacity,padding] duration-300 w-full",
              isExpanded ? "max-h-96 opacity-100" : "max-h-0 opacity-0 p-0",
            )}
          >
            <span className="whitespace-pre-wrap">
              tool: {toolCallRequest?.toolName}
            </span>
            <span className="whitespace-pre-wrap">
              parameters:{"\n"}
              {stringify(keyifyParameters(toolCallRequest?.parameters))}
            </span>
            {associatedToolResponse && (
              <>
                <span className="whitespace-pre-wrap font-medium">result:</span>
                <div className="whitespace-pre-wrap">
                  {!associatedToolResponse.content ? (
                    <span className="text-muted-foreground italic">
                      Empty response
                    </span>
                  ) : (
                    formatToolResult(associatedToolResponse.content)
                  )}
                </div>
              </>
            )}
          </div>
        </div>
      </div>
    );
  },
);

ToolcallInfo.displayName = "ToolcallInfo";

function keyifyParameters(parameters: TamboAI.ToolCallParameter[] | undefined) {
  if (!parameters) return;
  return Object.fromEntries(
    parameters.map((p) => [p.parameterName, p.parameterValue]),
  );
}

/**
 * Helper function to detect if content is JSON and format it nicely
 * @param content - The content to check and format
 * @returns Formatted content or original content if not JSON
 */
function formatToolResult(
  content: TamboThreadMessage["content"],
): React.ReactNode {
  if (!content) return content;

  const safeContent = getSafeContent(content);
  if (typeof safeContent !== "string") return safeContent;

  // Try to parse as JSON
  try {
    const parsed = JSON.parse(safeContent);
    return (
      <pre className="bg-muted/50 rounded-md p-3 text-xs overflow-x-auto overflow-y-auto max-w-full max-h-64">
        <code className="font-mono break-words whitespace-pre-wrap">
          {JSON.stringify(parsed, null, 2)}
        </code>
      </pre>
    );
  } catch {
    return safeContent;
  }
}

/**
 * Props for the MessageRenderedComponentArea component.
 * Extends standard HTMLDivElement attributes.
 */
export type MessageRenderedComponentAreaProps =
  React.HTMLAttributes<HTMLDivElement>;

/**
 * Displays the `renderedComponent` associated with an assistant message.
 * Shows a button to view in canvas if a canvas space exists, otherwise renders inline.
 * Only renders if the message role is 'assistant' and `message.renderedComponent` exists.
 * @component Message.RenderedComponentArea
 */
const MessageRenderedComponentArea = React.forwardRef<
  HTMLDivElement,
  MessageRenderedComponentAreaProps
>(({ className, children, ...props }, ref) => {
  const { message, role } = useMessageContext();
  const [canvasExists, setCanvasExists] = React.useState(false);

  // Check if canvas exists on mount and window resize
  React.useEffect(() => {
    const checkCanvasExists = () => {
      const canvas = document.querySelector('[data-canvas-space="true"]');
      setCanvasExists(!!canvas);
    };

    // Check on mount
    checkCanvasExists();

    // Set up resize listener
    window.addEventListener("resize", checkCanvasExists);

    // Clean up
    return () => {
      window.removeEventListener("resize", checkCanvasExists);
    };
  }, []);

  if (
    !message.renderedComponent ||
    role !== "assistant" ||
    message.isCancelled
  ) {
    return null;
  }

  return (
    <div
      ref={ref}
      className={cn("pt-2", className)}
      data-slot="message-rendered-component-area"
      {...props}
    >
      {children ??
        (canvasExists ? (
          <div className="flex justify-start pl-4">
            <button
              onClick={() => {
                if (typeof window !== "undefined") {
                  window.dispatchEvent(
                    new CustomEvent("tambo:showComponent", {
                      detail: {
                        messageId: message.id,
                        component: message.renderedComponent,
                      },
                    }),
                  );
                }
              }}
              className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-secondary transition-colors duration-200 cursor-pointer group"
              aria-label="View component in canvas"
            >
              View component
              <ExternalLink className="w-3.5 h-3.5" />
            </button>
          </div>
        ) : (
          <div className="w-full pt-4 px-2">{message.renderedComponent}</div>
        ))}
    </div>
  );
});
MessageRenderedComponentArea.displayName = "Message.RenderedComponentArea";

// --- Exports ---
export {
  LoadingIndicator,
  Message,
  MessageContent,
  MessageImages,
  MessageRenderedComponentArea,
  messageVariants,
  ToolcallInfo,
};
