// community/templates/sveltekit-starter/src/components/tambo/ThreadContent.svelte
<script lang="ts">
  import { cn } from "$lib/utils.js";
  import { getTamboContext } from "$lib/tambo/context.js";
  import Message from "./Message.svelte";
  import type { TamboThreadMessage } from "$lib/tambo/types.js";

  interface Props {
    variant?: "default" | "solid";
    class?: string;
  }

  let { variant = "default", class: className }: Props = $props();

  const tambo = getTamboContext();
  const { thread } = tambo;

  // Filter messages to exclude system messages and child messages
  const filteredMessages = $derived(
    thread.messages.filter(
      (message) => message.role !== "system" && !message.parentMessageId
    )
  );

  const isGenerating = $derived(!thread.isIdle);
</script>

<div class={cn("w-full", className)} data-slot="thread-content-container">
  <div class="flex flex-col gap-2" data-slot="thread-content-messages">
    {#each filteredMessages as message, index (message.id || `${message.role}-${index}`)}
      <div data-slot="thread-content-item">
        <Message
          role={message.role === "assistant" ? "assistant" : "user"}
          {message}
          {variant}
          isLoading={isGenerating && index === filteredMessages.length - 1}
          class={cn(
            "flex w-full",
            message.role === "assistant" ? "justify-start" : "justify-end"
          )}
        />
      </div>
    {/each}
  </div>
</div>

// community/templates/react-router-starter/app/components/tambo/thread-content.tsx
import { type TamboThreadMessage, useTambo } from "@tambo-ai/react";
import type { VariantProps } from "class-variance-authority";
import * as React from "react";
import {
	Message,
	MessageContent,
	MessageImages,
	MessageRenderedComponentArea,
	type messageVariants,
	ReasoningInfo,
	ToolcallInfo,
} from "@/components/tambo/message";
import { cn } from "@/lib/utils";

/**
 * @typedef ThreadContentContextValue
 * @property {Array} messages - Array of message objects in the thread
 * @property {boolean} isGenerating - Whether a response is being generated
 * @property {string|undefined} generationStage - Current generation stage
 * @property {VariantProps<typeof messageVariants>["variant"]} [variant] - Optional styling variant for messages
 */
interface ThreadContentContextValue {
	messages: TamboThreadMessage[];
	isGenerating: boolean;
	generationStage?: string;
	variant?: VariantProps<typeof messageVariants>["variant"];
}

/**
 * React Context for sharing thread data among sub-components.
 * @internal
 */
const ThreadContentContext =
	React.createContext<ThreadContentContextValue | null>(null);

/**
 * Hook to access the thread content context.
 * @returns {ThreadContentContextValue} The thread content context value.
 * @throws {Error} If used outside of ThreadContent.
 * @internal
 */
const useThreadContentContext = () => {
	const context = React.useContext(ThreadContentContext);
	if (!context) {
		throw new Error(
			"ThreadContent sub-components must be used within a ThreadContent",
		);
	}
	return context;
};

/**
 * Props for the ThreadContent component.
 * Extends standard HTMLDivElement attributes.
 */
export interface ThreadContentProps
	extends React.HTMLAttributes<HTMLDivElement> {
	/** Optional styling variant for the message container */
	variant?: VariantProps<typeof messageVariants>["variant"];
	/** The child elements to render within the container. */
	children?: React.ReactNode;
}

/**
 * The root container for thread content.
 * It establishes the context for its children using data from the Tambo hook.
 * @component ThreadContent
 * @example
 * ```tsx
 * <ThreadContent variant="solid">
 *   <ThreadContent.Messages />
 * </ThreadContent>
 * ```
 */
const ThreadContent = React.forwardRef<HTMLDivElement, ThreadContentProps>(
	({ children, className, variant, ...props }, ref) => {
		const { thread, generationStage, isIdle } = useTambo();
		const isGenerating = !isIdle;

		const contextValue = React.useMemo(
			() => ({
				messages: thread?.messages ?? [],
				isGenerating,
				generationStage,
				variant,
			}),
			[thread?.messages, isGenerating, generationStage, variant],
		);

		return (
			<ThreadContentContext.Provider value={contextValue}>
				<div
					ref={ref}
					className={cn("w-full", className)}
					data-slot="thread-content-container"
					{...props}
				>
					{children}
				</div>
			</ThreadContentContext.Provider>
		);
	},
);
ThreadContent.displayName = "ThreadContent";

/**
 * Props for the ThreadContentMessages component.
 * Extends standard HTMLDivElement attributes.
 */
export type ThreadContentMessagesProps = React.HTMLAttributes<HTMLDivElement>;

/**
 * Renders the list of messages in the thread.
 * Automatically connects to the context to display messages.
 * @component ThreadContent.Messages
 * @example
 * ```tsx
 * <ThreadContent>
 *   <ThreadContent.Messages />
 * </ThreadContent>
 * ```
 */
const ThreadContentMessages = React.forwardRef<
	HTMLDivElement,
	ThreadContentMessagesProps
>(({ className, ...props }, ref) => {
	const { messages, isGenerating, variant } = useThreadContentContext();

	const filteredMessages = messages.filter(
		(message) => message.role !== "system" && !message.parentMessageId,
	);

	return (
		<div
			ref={ref}
			className={cn("flex flex-col gap-2", className)}
			data-slot="thread-content-messages"
			{...props}
		>
			{filteredMessages.map((message, index) => {
				return (
					<div
						key={
							message.id ??
							`${message.role}-${message.createdAt ?? `${index}`}-${message.content?.toString().substring(0, 10)}`
						}
						data-slot="thread-content-item"
					>
						<Message
							role={message.role === "assistant" ? "assistant" : "user"}
							message={message}
							variant={variant}
							isLoading={isGenerating && index === filteredMessages.length - 1}
							className={cn(
								"flex w-full",
								message.role === "assistant" ? "justify-start" : "justify-end",
							)}
						>
							<div
								className={cn(
									"flex flex-col",
									message.role === "assistant" ? "w-full" : "max-w-3xl",
								)}
							>
								<ReasoningInfo />
								<MessageImages />
								<MessageContent
									className={
										message.role === "assistant"
											? "text-foreground font-sans"
											: "text-foreground bg-container hover:bg-backdrop font-sans"
									}
								/>
								<ToolcallInfo />
								<MessageRenderedComponentArea className="w-full" />
							</div>
						</Message>
					</div>
				);
			})}
		</div>
	);
});
ThreadContentMessages.displayName = "ThreadContent.Messages";

export { ThreadContent, ThreadContentMessages };
