// community/templates/sveltekit-starter/src/components/tambo/Message.svelte
<script lang="ts">
  import { cn } from "$lib/utils.js";
  import MessageContent from "./MessageContent.svelte";
  import { ChevronDown, Check, Loader2, X } from "lucide-svelte";
  import type { TamboThreadMessage, ContentPart } from "$lib/tambo/types.js";
  import { getTamboContext } from "$lib/tambo/context.js";
  import type { Snippet } from "svelte";

  type ToolCallRequest = NonNullable<TamboThreadMessage["toolCallRequest"]>;

  interface Props {
    role: "user" | "assistant";
    message: TamboThreadMessage;
    variant?: "default" | "solid";
    isLoading?: boolean;
    class?: string;
    children?: Snippet;
  }

  let {
    role,
    message,
    variant = "default",
    isLoading = false,
    class: className,
    children,
  }: Props = $props();

  // Don't render tool messages directly
  const shouldRender = $derived(message.role !== "tool");

  // Tool call state
  let toolExpanded = $state(false);

  /**
   * Get tool call request from message
   */
  function getToolCallRequest(): ToolCallRequest | undefined {
    return message.toolCallRequest ?? message.component?.toolCallRequest;
  }

  /**
   * Get images from message content
   */
  function getMessageImages(
    content: string | ContentPart[] | null | undefined
  ): string[] {
    if (!content || !Array.isArray(content)) return [];
    return content
      .filter((item) => item?.type === "image_url" && item.image_url?.url)
      .map((item) => (item as { type: "image_url"; image_url: { url: string } }).image_url.url);
  }

  const images = $derived(getMessageImages(message.content));
  const hasToolCall = $derived(!!getToolCallRequest());
  const toolCallRequest = $derived(getToolCallRequest());

  // Get component from registry if rendered
  const tambo = getTamboContext();

  const registeredComponent = $derived(
    message.component?.name ? tambo.thread.getComponent(message.component.name) : undefined
  );

  /**
   * Format tool parameters for display
   */
  function formatParameters(
    params: ToolCallRequest["parameters"]
  ): Record<string, unknown> {
    if (!params) return {};
    return Object.fromEntries(params.map((p) => [p.parameterName, p.parameterValue]));
  }
</script>

{#if shouldRender}
  <div
    class={cn(
      "flex",
      variant === "solid" &&
        "[&>div>div:first-child]:shadow-md [&>div>div:first-child]:bg-container/50",
      className
    )}
    data-message-role={role}
    data-message-id={message.id}
  >
    {#if children}
      {@render children()}
    {:else}
      <div class={cn("flex flex-col", role === "assistant" ? "w-full" : "max-w-3xl")}>
        <!-- Reasoning info (for models with extended thinking) -->
        {#if message.reasoning && message.reasoning.length > 0}
          <div class="flex flex-col items-start text-xs opacity-50 mb-2">
            <button
              type="button"
              class="flex items-center gap-1 cursor-pointer hover:bg-muted-foreground/10 rounded-md px-3 py-1"
              onclick={() => (toolExpanded = !toolExpanded)}
            >
              <span class={isLoading ? "animate-thinking-gradient" : ""}>
                {isLoading ? "Thinking..." : "Done Thinking"}
                {message.reasoning.length > 1 ? `(${message.reasoning.length} steps)` : ""}
              </span>
              <ChevronDown
                class={cn("w-3 h-3 transition-transform duration-200", !toolExpanded && "-rotate-90")}
              />
            </button>
            {#if toolExpanded}
              <div class="flex flex-col gap-1 px-3 py-3 max-h-96 overflow-auto">
                {#each message.reasoning as step, index}
                  <div class="flex flex-col gap-1">
                    {#if message.reasoning.length > 1}
                      <span class="text-muted-foreground text-xs font-medium">Step {index + 1}:</span>
                    {/if}
                    <div class="bg-muted/50 rounded-md p-3 text-xs whitespace-pre-wrap">
                      {step}
                    </div>
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        {/if}

        <!-- Images -->
        {#if images.length > 0}
          <div class="flex flex-wrap gap-2 mb-2">
            {#each images as imageUrl, index}
              <div class="w-32 h-32 rounded-md overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                <img
                  src={imageUrl}
                  alt={`Image ${index + 1}`}
                  class="w-full h-full object-cover"
                />
              </div>
            {/each}
          </div>
        {/if}

        <!-- Message content -->
        <MessageContent
          content={message.content}
          {isLoading}
          class={role === "assistant"
            ? "text-foreground font-sans"
            : "text-foreground bg-container hover:bg-backdrop font-sans"}
        />

        <!-- Tool call info -->
        {#if hasToolCall && role === "assistant"}
          <div class="flex flex-col items-start text-xs opacity-50 mt-2">
            <button
              type="button"
              class="flex items-center gap-1 cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 rounded-md p-1"
              onclick={() => (toolExpanded = !toolExpanded)}
            >
              {#if message.error}
                <X class="w-3 h-3 text-red-500" />
              {:else if isLoading}
                <Loader2 class="w-3 h-3 animate-spin" />
              {:else}
                <Check class="w-3 h-3 text-green-500" />
              {/if}
              <span>
                {isLoading ? "Calling" : "Called"} {toolCallRequest?.toolName ?? "tool"}
              </span>
              <ChevronDown
                class={cn("w-3 h-3 transition-transform duration-200", !toolExpanded && "-rotate-90")}
              />
            </button>
            {#if toolExpanded && toolCallRequest}
              <div class="flex flex-col gap-1 p-3 pl-7 overflow-auto">
                <span class="whitespace-pre-wrap pl-2">tool: {toolCallRequest.toolName}</span>
                <span class="whitespace-pre-wrap pl-2">
                  parameters: {JSON.stringify(formatParameters(toolCallRequest.parameters), null, 2)}
                </span>
              </div>
            {/if}
          </div>
        {/if}

        <!-- Rendered component -->
        {#if message.component && registeredComponent && role === "assistant" && !message.isCancelled}
          {@const DynamicComponent = registeredComponent.component}
          <div class="w-full pt-2 px-2">
            <DynamicComponent
              {...message.component.props}
            />
          </div>
        {/if}

        <!-- Cancelled indicator -->
        {#if message.isCancelled}
          <span class="text-muted-foreground text-xs px-4">cancelled</span>
        {/if}
      </div>
    {/if}
  </div>
{/if}

// community/templates/remix-supabase-bookmarks/app/components/message.tsx
import { useTambo, type TamboThreadMessage } from "@tambo-ai/react";
import { useMemo, useState } from "react";
import { Streamdown } from "streamdown";
import { cn } from "~/lib/utils";
import { Loader2, Check, X, ChevronDown } from "lucide-react";
import type TamboAI from "@tambo-ai/typescript-sdk";
import stringify from "json-stringify-pretty-compact";

// ============================================================================
// Utilities
// ============================================================================

function getMessageTextContent(message: TamboThreadMessage): string {
  const raw = message.content;
  if (!raw) return "";
  if (typeof raw === "string") return raw;
  if (Array.isArray(raw)) {
    return raw
      .filter(
        (part): part is { type: "text"; text: string } =>
          part?.type === "text" && typeof part.text === "string",
      )
      .map((part) => part.text)
      .join(" ");
  }
  return "";
}

function getToolCallRequest(
  message: TamboThreadMessage,
): TamboAI.ToolCallRequest | undefined {
  return message.toolCallRequest ?? message.component?.toolCallRequest;
}

function keyifyParameters(parameters: TamboAI.ToolCallParameter[] | undefined) {
  if (!parameters) return undefined;
  return Object.fromEntries(
    parameters.map((p) => [p.parameterName, p.parameterValue]),
  );
}

function extractContentString(
  content: TamboThreadMessage["content"],
): string | null {
  if (!content) return null;
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content
      .map((item) => {
        if (item?.type === "text") {
          return item.text ?? "";
        }
        return "";
      })
      .join("");
  }
  return null;
}

function formatToolResult(
  content: TamboThreadMessage["content"],
): React.ReactNode {
  const contentString = extractContentString(content);

  if (contentString) {
    try {
      const parsed = JSON.parse(contentString);
      return (
        <pre className="text-xs bg-slate-50 p-2 rounded overflow-auto">
          {stringify(parsed)}
        </pre>
      );
    } catch {
      return <div className="text-xs whitespace-pre-wrap">{contentString}</div>;
    }
  }

  return null;
}

function getMessageImages(content: TamboThreadMessage["content"]): string[] {
  if (!content || !Array.isArray(content)) return [];
  return content
    .filter(
      (item): item is { type: "image_url"; image_url: { url: string } } =>
        item?.type === "image_url" && !!item.image_url?.url,
    )
    .map((item) => item.image_url.url);
}

// ============================================================================
// Components
// ============================================================================

function MessageImages({ message }: { message: TamboThreadMessage }) {
  const images = getMessageImages(message.content);

  if (images.length === 0) return null;

  return (
    <div className="flex flex-wrap gap-2 mb-2">
      {images.map((imageUrl, index) => (
        <div
          key={index}
          className="w-32 h-32 rounded-md overflow-hidden shadow-sm hover:shadow-md transition-shadow duration-200"
        >
          <img
            src={imageUrl}
            alt={`Image ${index + 1}`}
            className="w-full h-full object-cover"
          />
        </div>
      ))}
    </div>
  );
}

function LoadingIndicator() {
  return (
    <div className="flex items-center gap-1">
      <span className="h-2 w-2 animate-bounce rounded-full bg-slate-600 [animation-delay:-0.3s]" />
      <span className="h-2 w-2 animate-bounce rounded-full bg-slate-600 [animation-delay:-0.2s]" />
      <span className="h-2 w-2 animate-bounce rounded-full bg-slate-600 [animation-delay:-0.1s]" />
    </div>
  );
}

function UserMessage({ message }: { message: TamboThreadMessage }) {
  const content = useMemo(() => getMessageTextContent(message), [message]);
  const images = useMemo(() => getMessageImages(message.content), [message]);

  if (!content.trim() && images.length === 0) return null;

  return (
    <div className="flex justify-end">
      <div className="max-w-[80%] space-y-2">
        {images.length > 0 && (
          <div className="flex flex-wrap gap-2 justify-end">
            {images.map((imageUrl, index) => (
              <div
                key={index}
                className="w-32 h-32 rounded-md overflow-hidden shadow-sm"
              >
                <img
                  src={imageUrl}
                  alt={`Image ${index + 1}`}
                  className="w-full h-full object-cover"
                />
              </div>
            ))}
          </div>
        )}
        {content.trim() && (
          <div className="rounded-2xl bg-slate-900 px-4 py-3 text-white">
            <div className="text-sm">{content}</div>
          </div>
        )}
      </div>
    </div>
  );
}

function AssistantMessage({
  message,
  isLoading,
}: {
  message: TamboThreadMessage;
  isLoading: boolean;
}) {
  const content = useMemo(() => getMessageTextContent(message), [message]);
  const hasContent = content.trim().length > 0;

  // Skip if this message has a rendered component
  if (message.renderedComponent) return null;

  // Show loading dots only when streaming text (no tool call active)
  const hasToolCall =
    message.toolCallRequest ?? message.component?.toolCallRequest;
  const showLoading = isLoading && !hasContent && !hasToolCall;

  if (!showLoading && !hasContent) return null;

  return (
    <div className="flex justify-start">
      <div className="max-w-[80%] rounded-2x py-2 text-black">
        {showLoading ? (
          <LoadingIndicator />
        ) : (
          <div className="prose prose-sm max-w-none prose-p:my-1 prose-ul:my-1 prose-li:my-0">
            <Streamdown>{content}</Streamdown>
          </div>
        )}
      </div>
    </div>
  );
}

function ToolCallInfo({
  message,
  isLoading,
}: {
  message: TamboThreadMessage;
  isLoading: boolean;
}) {
  const [isExpanded, setIsExpanded] = useState(false);
  const { thread } = useTambo();

  // Find associated tool response
  const associatedToolResponse = useMemo(() => {
    if (!thread?.messages) return null;
    const currentIndex = thread.messages.findIndex((m) => m.id === message.id);
    if (currentIndex === -1) return null;

    for (let i = currentIndex + 1; i < thread.messages.length; i++) {
      const nextMessage = thread.messages[i];
      if (nextMessage.role === "tool") {
        return nextMessage;
      }
      if (nextMessage.role === "assistant" && getToolCallRequest(nextMessage)) {
        break;
      }
    }
    return null;
  }, [message.id, thread?.messages]);

  const toolCallRequest = getToolCallRequest(message);
  if (!toolCallRequest) return null;

  const hasToolError = !!message.error;

  const toolStatusMessage = isLoading
    ? `Calling ${toolCallRequest.toolName}`
    : `Called ${toolCallRequest.toolName}`;

  return (
    <div className="flex flex-col items-start text-xs opacity-70 mt-1">
      <button
        type="button"
        onClick={() => setIsExpanded(!isExpanded)}
        className="flex items-center gap-1.5 hover:bg-slate-100 rounded px-2 py-1 transition-colors"
      >
        {hasToolError ? (
          <X className="w-3 h-3 text-red-500" />
        ) : isLoading ? (
          <Loader2 className="w-3 h-3 animate-spin text-slate-500" />
        ) : (
          <Check className="w-3 h-3 text-green-500" />
        )}
        <span className="text-slate-600">{toolStatusMessage}</span>
        <ChevronDown
          className={cn(
            "w-3 h-3 transition-transform",
            !isExpanded && "-rotate-90",
          )}
        />
      </button>

      {isExpanded && (
        <div className="flex flex-col gap-2 pl-6 pr-2 py-2 text-slate-600 w-full">
          <div>
            <span className="font-medium">Tool:</span>{" "}
            {toolCallRequest.toolName}
          </div>
          <div>
            <span className="font-medium">Parameters:</span>
            <pre className="text-xs bg-slate-50 p-2 rounded mt-1 overflow-auto">
              {stringify(keyifyParameters(toolCallRequest.parameters))}
            </pre>
          </div>
          {associatedToolResponse && (
            <div>
              <span className="font-medium">Result:</span>
              <div className="mt-1">
                {!associatedToolResponse.content ? (
                  <span className="italic text-slate-400">Empty response</span>
                ) : (
                  formatToolResult(associatedToolResponse.content)
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function RenderedComponent({ message }: { message: TamboThreadMessage }) {
  if (!message.renderedComponent) return null;

  return <div className="w-full">{message.renderedComponent}</div>;
}

export function Message({
  message,
  isLoading,
}: {
  message: TamboThreadMessage;
  isLoading: boolean;
}) {
  if (message.role === "user") {
    return <UserMessage message={message} />;
  }

  return (
    <div className="space-y-1">
      <MessageImages message={message} />
      <AssistantMessage message={message} isLoading={isLoading} />
      <ToolCallInfo message={message} isLoading={isLoading} />
      <RenderedComponent message={message} />
    </div>
  );
}
