// community/templates/sveltekit-starter/src/components/tambo/ThreadHistory.svelte
<script lang="ts">
  import { cn } from "$lib/utils.js";
  import { useTamboThread, type TamboThread } from "@tambo-ai/svelte";
  import {
    ArrowLeftToLine,
    ArrowRightToLine,
    MoreHorizontal,
    Pencil,
    PlusIcon,
    SearchIcon,
    Sparkles,
  } from "lucide-svelte";
  import { onMount } from "svelte";

  interface Props {
    contextKey?: string;
    position?: "left" | "right";
    defaultCollapsed?: boolean;
    onThreadChange?: () => void;
    class?: string;
  }

  let {
    contextKey,
    position = "left",
    defaultCollapsed = true,
    onThreadChange,
    class: className,
  }: Props = $props();

  const thread = useTamboThread();

  let isCollapsed = $state(true);
  let searchQuery = $state("");
  let isLoading = $state(false);
  let threads = $state<TamboThread[]>([]);
  let editingThread = $state<TamboThread | null>(null);
  let newName = $state("");
  let showDropdown = $state<string | null>(null);

  // Update CSS variable when collapsed state changes
  $effect(() => {
    const sidebarWidth = isCollapsed ? "3rem" : "16rem";
    document.documentElement.style.setProperty("--sidebar-width", sidebarWidth);
  });

  // Fetch threads on mount
  onMount(async () => {
    await fetchThreads();
  });

  async function fetchThreads() {
    isLoading = true;
    try {
      threads = await thread.fetchThreads(contextKey);
    } catch (err) {
      console.error("Failed to fetch threads:", err);
    } finally {
      isLoading = false;
    }
  }

  async function handleNewThread() {
    try {
      thread.startNewThread(contextKey);
      await fetchThreads();
      onThreadChange?.();
    } catch (err) {
      console.error("Failed to create new thread:", err);
    }
  }

  async function handleSwitchThread(threadId: string) {
    try {
      await thread.switchThread(threadId);
      onThreadChange?.();
    } catch (err) {
      console.error("Failed to switch thread:", err);
    }
  }

  async function handleRename(t: TamboThread) {
    editingThread = t;
    newName = t.name ?? "";
    showDropdown = null;
  }

  async function handleGenerateName(t: TamboThread) {
    try {
      await thread.generateThreadName(t.id);
      await fetchThreads();
    } catch (err) {
      console.error("Failed to generate name:", err);
    }
    showDropdown = null;
  }

  async function handleNameSubmit(e: Event) {
    e.preventDefault();
    if (!editingThread) return;

    try {
      await thread.updateThreadName(newName, editingThread.id);
      await fetchThreads();
      editingThread = null;
    } catch (err) {
      console.error("Failed to rename thread:", err);
    }
  }

  // Filter threads based on search
  const filteredThreads = $derived(
    isCollapsed
      ? []
      : threads.filter((t) => {
          const query = searchQuery.toLowerCase();
          return (
            t.id.toLowerCase().includes(query) ||
            (t.name?.toLowerCase().includes(query) ?? false)
          );
        }),
  );

  function formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleString(undefined, {
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
    });
  }
</script>

<div
  class={cn(
    "border-flat bg-container h-full transition-all duration-300 flex-none",
    position === "left" ? "border-r" : "border-l",
    isCollapsed ? "w-12" : "w-64",
    className,
  )}
>
  <div class={cn("flex flex-col h-full", isCollapsed ? "py-4 px-2" : "p-4")}>
    <!-- Header -->
    <div class="flex items-center mb-4 relative p-1">
      <h2
        class={cn(
          "text-sm text-muted-foreground whitespace-nowrap",
          isCollapsed
            ? "opacity-0 max-w-0 overflow-hidden"
            : "opacity-100 max-w-none transition-all duration-300 delay-75",
        )}
      >
        Tambo Conversations
      </h2>
      <button
        type="button"
        onclick={() => (isCollapsed = !isCollapsed)}
        class={cn(
          "bg-container p-1 hover:bg-backdrop transition-colors rounded-md cursor-pointer absolute flex items-center justify-center",
          position === "left" ? "right-1" : "left-0",
        )}
      >
        {#if isCollapsed}
          <ArrowRightToLine
            class={cn("h-4 w-4", position === "right" && "rotate-180")}
          />
        {:else}
          <ArrowLeftToLine
            class={cn("h-4 w-4", position === "right" && "rotate-180")}
          />
        {/if}
      </button>
    </div>

    <!-- New Thread Button -->
    <button
      type="button"
      onclick={handleNewThread}
      class={cn(
        "flex items-center rounded-md mb-4 hover:bg-backdrop transition-colors cursor-pointer relative",
        isCollapsed ? "p-1 justify-center" : "p-2 gap-2",
      )}
    >
      <PlusIcon class="h-4 w-4 bg-green-600 rounded-full text-white" />
      <span
        class={cn(
          "text-sm font-medium whitespace-nowrap absolute left-8 pb-[2px]",
          isCollapsed
            ? "opacity-0 max-w-0 overflow-hidden pointer-events-none"
            : "opacity-100 transition-all duration-300 delay-100",
        )}
      >
        New thread
      </span>
    </button>

    <!-- Search -->
    <div class="mb-4 relative">
      {#if isCollapsed}
        <button
          type="button"
          onclick={() => (isCollapsed = false)}
          class="p-1 hover:bg-backdrop rounded-md cursor-pointer absolute left-1/2 -translate-x-1/2"
        >
          <SearchIcon class="h-4 w-4 text-gray-400" />
        </button>
      {:else}
        <div class="relative">
          <div
            class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none"
          >
            <SearchIcon class="h-4 w-4 text-gray-400" />
          </div>
          <input
            type="text"
            class="pl-10 pr-4 py-2 w-full text-sm rounded-md bg-container focus:outline-none"
            placeholder="Search..."
            bind:value={searchQuery}
          />
        </div>
      {/if}
    </div>

    <!-- Thread List -->
    <div
      class={cn(
        "overflow-y-auto flex-1 transition-all duration-300 ease-in-out",
        isCollapsed
          ? "opacity-0 max-h-0 overflow-hidden pointer-events-none"
          : "opacity-100 max-h-full pointer-events-auto",
      )}
    >
      {#if isLoading}
        <div class="text-sm text-muted-foreground p-2">Loading threads...</div>
      {:else if filteredThreads.length === 0}
        <div class="text-sm text-muted-foreground p-2">
          {searchQuery ? "No matching threads" : "No previous threads"}
        </div>
      {:else}
        <div class="space-y-1">
          {#each filteredThreads as t (t.id)}
            <div
              role="button"
              tabindex="0"
              class={cn(
                "p-2 rounded-md hover:bg-backdrop cursor-pointer group flex items-center justify-between",
                thread.currentThreadId === t.id && "bg-muted",
                editingThread?.id === t.id && "bg-muted",
              )}
              onclick={() => handleSwitchThread(t.id)}
              onkeydown={(e) => e.key === "Enter" && handleSwitchThread(t.id)}
            >
              <div class="text-sm flex-1">
                {#if editingThread?.id === t.id}
                  <form onsubmit={handleNameSubmit} class="flex flex-col gap-1">
                    <input
                      type="text"
                      bind:value={newName}
                      class="w-full bg-background px-1 text-sm font-medium focus:outline-none rounded-sm"
                      onclick={(e) => e.stopPropagation()}
                      placeholder="Thread name..."
                    />
                    <p class="text-xs text-muted-foreground truncate">
                      {formatDate(t.createdAt)}
                    </p>
                  </form>
                {:else}
                  <span class="font-medium line-clamp-1">
                    {t.name ?? `Thread ${t.id.substring(0, 8)}`}
                  </span>
                  <p class="text-xs text-muted-foreground truncate mt-1">
                    {formatDate(t.createdAt)}
                  </p>
                {/if}
              </div>

              <!-- Options dropdown -->
              <div class="relative">
                <button
                  type="button"
                  class="p-1 hover:bg-backdrop rounded-md opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                  onclick={(e) => {
                    e.stopPropagation();
                    showDropdown = showDropdown === t.id ? null : t.id;
                  }}
                >
                  <MoreHorizontal class="h-4 w-4 text-muted-foreground" />
                </button>

                {#if showDropdown === t.id}
                  <div
                    class="absolute right-0 top-8 min-w-[160px] text-xs bg-popover rounded-md p-1 shadow-md border border-border z-10"
                  >
                    <button
                      type="button"
                      class="flex items-center gap-2 px-2 py-1.5 w-full text-left text-foreground hover:bg-backdrop rounded-sm cursor-pointer"
                      onclick={(e) => {
                        e.stopPropagation();
                        handleRename(t);
                      }}
                    >
                      <Pencil class="h-3 w-3" />
                      Rename
                    </button>
                    <button
                      type="button"
                      class="flex items-center gap-2 px-2 py-1.5 w-full text-left text-foreground hover:bg-backdrop rounded-sm cursor-pointer"
                      onclick={(e) => {
                        e.stopPropagation();
                        handleGenerateName(t);
                      }}
                    >
                      <Sparkles class="h-3 w-3" />
                      Generate Name
                    </button>
                  </div>
                {/if}
              </div>
            </div>
          {/each}
        </div>
      {/if}
    </div>
  </div>
</div>

// showcase/src/components/ui/thread-history.tsx
"use client";

import { cn } from "@/lib/utils";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import {
  type TamboThread,
  useTamboThread,
  useTamboThreadList,
} from "@tambo-ai/react";
import {
  ArrowLeftToLine,
  ArrowRightToLine,
  MoreHorizontal,
  Pencil,
  PlusIcon,
  SearchIcon,
  Sparkles,
} from "lucide-react";
import React, { useMemo } from "react";

/**
 * Context for sharing thread history state and functions
 */
interface ThreadHistoryContextValue {
  threads: { items?: TamboThread[] } | null | undefined;
  isLoading: boolean;
  error: Error | null;
  refetch: () => Promise<unknown>;
  currentThread: TamboThread;
  switchCurrentThread: (threadId: string) => void;
  startNewThread: () => void;
  searchQuery: string;
  setSearchQuery: React.Dispatch<React.SetStateAction<string>>;
  isCollapsed: boolean;
  setIsCollapsed: React.Dispatch<React.SetStateAction<boolean>>;
  onThreadChange?: () => void;
  contextKey?: string;
  position?: "left" | "right";
  updateThreadName: (newName: string, threadId?: string) => Promise<void>;
  generateThreadName: (threadId: string) => Promise<TamboThread>;
}

const ThreadHistoryContext =
  React.createContext<ThreadHistoryContextValue | null>(null);

const useThreadHistoryContext = () => {
  const context = React.useContext(ThreadHistoryContext);
  if (!context) {
    throw new Error(
      "ThreadHistory components must be used within ThreadHistory",
    );
  }
  return context;
};

/**
 * Root component that provides context for thread history
 */
interface ThreadHistoryProps extends React.HTMLAttributes<HTMLDivElement> {
  contextKey?: string;
  onThreadChange?: () => void;
  children?: React.ReactNode;
  defaultCollapsed?: boolean;
  position?: "left" | "right";
}

const ThreadHistory = React.forwardRef<HTMLDivElement, ThreadHistoryProps>(
  (
    {
      className,
      contextKey,
      onThreadChange,
      defaultCollapsed = true,
      position = "left",
      children,
      ...props
    },
    ref,
  ) => {
    const [searchQuery, setSearchQuery] = React.useState("");
    const [isCollapsed, setIsCollapsed] = React.useState(defaultCollapsed);
    const [shouldFocusSearch, setShouldFocusSearch] = React.useState(false);

    const {
      data: threads,
      isLoading,
      error,
      refetch,
    } = useTamboThreadList({ contextKey });

    const {
      switchCurrentThread,
      startNewThread,
      thread: currentThread,
      updateThreadName,
      generateThreadName,
    } = useTamboThread();

    // Update CSS variable when sidebar collapses/expands
    React.useEffect(() => {
      const sidebarWidth = isCollapsed ? "3rem" : "16rem";
      document.documentElement.style.setProperty(
        "--sidebar-width",
        sidebarWidth,
      );
    }, [isCollapsed]);

    // Focus search input when expanded from collapsed state
    React.useEffect(() => {
      if (!isCollapsed && shouldFocusSearch) {
        setShouldFocusSearch(false);
      }
    }, [isCollapsed, shouldFocusSearch]);

    const contextValue = React.useMemo(
      () => ({
        threads,
        isLoading,
        error,
        refetch,
        currentThread,
        switchCurrentThread,
        startNewThread,
        searchQuery,
        setSearchQuery,
        isCollapsed,
        setIsCollapsed,
        onThreadChange,
        contextKey,
        position,
        updateThreadName,
        generateThreadName,
      }),
      [
        threads,
        isLoading,
        error,
        refetch,
        currentThread,
        switchCurrentThread,
        startNewThread,
        searchQuery,
        isCollapsed,
        onThreadChange,
        contextKey,
        position,
        updateThreadName,
        generateThreadName,
      ],
    );

    return (
      <ThreadHistoryContext.Provider
        value={contextValue as ThreadHistoryContextValue}
      >
        <div
          ref={ref}
          className={cn(
            "border-flat bg-container h-full absolute top-0 transition-all duration-300",
            position === "left" ? "border-r left-0" : "border-l right-0",
            isCollapsed ? "w-12" : "w-64",
            className,
          )}
          {...props}
        >
          <div
            className={cn(
              "flex flex-col h-full",
              isCollapsed ? "py-4 px-2" : "p-4",
            )} // py-4 px-2 is for better alignment when isCollapsed
          >
            {children}
          </div>
        </div>
      </ThreadHistoryContext.Provider>
    );
  },
);
ThreadHistory.displayName = "ThreadHistory";

/**
 * Header component with title and collapse toggle
 */
const ThreadHistoryHeader = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => {
  const {
    isCollapsed,
    setIsCollapsed,
    position = "left",
  } = useThreadHistoryContext();

  return (
    <div
      ref={ref}
      className={cn(
        "flex items-center mb-4 relative",
        isCollapsed ? "p-1" : "p-1",
        className,
      )}
      {...props}
    >
      <h2
        className={cn(
          "text-sm text-muted-foreground whitespace-nowrap ",
          isCollapsed
            ? "opacity-0 max-w-0 overflow-hidden "
            : "opacity-100 max-w-none transition-all duration-300 delay-75",
        )}
      >
        Tambo Conversations
      </h2>
      <button
        onClick={() => setIsCollapsed(!isCollapsed)}
        className={cn(
          `bg-container p-1 hover:bg-backdrop transition-colors rounded-md cursor-pointer absolute flex items-center justify-center`,
          position === "left" ? "right-1" : "left-0",
        )}
        aria-label={isCollapsed ? "Expand sidebar" : "Collapse sidebar"}
      >
        {isCollapsed ? (
          <ArrowRightToLine
            className={cn("h-4 w-4", position === "right" && "rotate-180")}
          />
        ) : (
          <ArrowLeftToLine
            className={cn("h-4 w-4", position === "right" && "rotate-180")}
          />
        )}
      </button>
    </div>
  );
});
ThreadHistoryHeader.displayName = "ThreadHistory.Header";

/**
 * Button to create a new thread
 */
const ThreadHistoryNewButton = React.forwardRef<
  HTMLButtonElement,
  React.ButtonHTMLAttributes<HTMLButtonElement>
>(({ ...props }, ref) => {
  const { isCollapsed, startNewThread, refetch, onThreadChange } =
    useThreadHistoryContext();

  const handleNewThread = React.useCallback(
    async (e?: React.MouseEvent) => {
      if (e) e.stopPropagation();

      try {
        await startNewThread();
        await refetch();
        onThreadChange?.();
      } catch (error) {
        console.error("Failed to create new thread:", error);
      }
    },
    [startNewThread, refetch, onThreadChange],
  );

  React.useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.altKey && event.shiftKey && event.key === "n") {
        event.preventDefault();
        handleNewThread();
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [handleNewThread]);

  return (
    <button
      ref={ref}
      onClick={handleNewThread}
      className={cn(
        "flex items-center rounded-md mb-4 hover:bg-backdrop transition-colors cursor-pointer relative",
        isCollapsed ? "p-1 justify-center" : "p-2 gap-2",
      )}
      title="New thread"
      {...props}
    >
      <PlusIcon className="h-4 w-4 bg-green-600 rounded-full text-white" />
      <span
        className={cn(
          "text-sm font-medium whitespace-nowrap absolute left-8 pb-[2px] ",
          isCollapsed
            ? "opacity-0 max-w-0 overflow-hidden pointer-events-none"
            : "opacity-100 transition-all duration-300 delay-100",
        )}
      >
        New thread
      </span>
    </button>
  );
});
ThreadHistoryNewButton.displayName = "ThreadHistory.NewButton";

/**
 * Search input for filtering threads
 */
const ThreadHistorySearch = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => {
  const { isCollapsed, setIsCollapsed, searchQuery, setSearchQuery } =
    useThreadHistoryContext();
  const searchInputRef = React.useRef<HTMLInputElement>(null);

  const expandOnSearch = () => {
    if (isCollapsed) {
      setIsCollapsed(false);
      setTimeout(() => {
        searchInputRef.current?.focus();
      }, 300); // Wait for animation
    }
  };

  return (
    <div ref={ref} className={cn("mb-4 relative", className)} {...props}>
      {/*visible when collapsed */}
      <button
        onClick={expandOnSearch}
        className={cn(
          "p-1 hover:bg-backdrop rounded-md cursor-pointer absolute left-1/2 -translate-x-1/2",
          isCollapsed
            ? "opacity-100 pointer-events-auto transition-all duration-300"
            : "opacity-0 pointer-events-none",
        )}
        title="Search threads"
      >
        <SearchIcon className="h-4 w-4 text-gray-400" />
      </button>

      {/*visible when expanded with delay */}

      <div
        className={cn(
          //using this as wrapper
          isCollapsed
            ? "opacity-0 pointer-events-none"
            : "opacity-100 delay-100 transition-all duration-500",
        )}
      >
        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <SearchIcon className="h-4 w-4 text-gray-400" />
        </div>
        <input
          ref={searchInputRef}
          type="text"
          className="pl-10 pr-4 py-2 w-full text-sm rounded-md bg-container focus:outline-none"
          placeholder="Search..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
        />
      </div>
    </div>
  );
});
ThreadHistorySearch.displayName = "ThreadHistory.Search";

/**
 * List of thread items
 */
const ThreadHistoryList = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => {
  const {
    threads,
    isLoading,
    error,
    isCollapsed,
    searchQuery,
    currentThread,
    switchCurrentThread,
    onThreadChange,
    updateThreadName,
    generateThreadName,
    refetch,
  } = useThreadHistoryContext();

  const [editingThread, setEditingThread] = React.useState<TamboThread | null>(
    null,
  );
  const [newName, setNewName] = React.useState("");
  const inputRef = React.useRef<HTMLInputElement>(null);

  // Handle click outside name editing input
  React.useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        editingThread &&
        inputRef.current &&
        !inputRef.current.contains(event.target as Node)
      ) {
        setEditingThread(null);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [editingThread]);

  // Focus input when entering edit mode
  React.useEffect(() => {
    if (editingThread) {
      const timer = setTimeout(() => {
        inputRef.current?.focus();
      }, 100);
      return () => clearTimeout(timer);
    }
  }, [editingThread]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Escape") {
      setEditingThread(null);
    }
  };

  // Filter threads based on search query
  const filteredThreads = useMemo(() => {
    // While collapsed we do not need the list, avoid extra work.
    if (isCollapsed) return [];

    if (!threads?.items) return [];

    const query = searchQuery.toLowerCase();
    return threads.items.filter((thread: TamboThread) => {
      const nameMatches = thread.name?.toLowerCase().includes(query) ?? false;
      const idMatches = thread.id.toLowerCase().includes(query);

      return idMatches ? true : nameMatches;
    });
  }, [isCollapsed, threads, searchQuery]);

  const handleSwitchThread = async (threadId: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();

    try {
      switchCurrentThread(threadId);
      onThreadChange?.();
    } catch (error) {
      console.error("Failed to switch thread:", error);
    }
  };

  const handleRename = (thread: TamboThread) => {
    setEditingThread(thread);
    setNewName(thread.name ?? "");
  };

  const handleGenerateName = async (thread: TamboThread) => {
    try {
      await generateThreadName(thread.id);
      await refetch();
    } catch (error) {
      console.error("Failed to generate name:", error);
    }
  };

  const handleNameSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingThread) return;

    try {
      await updateThreadName(newName, editingThread.id);
      await refetch();
      setEditingThread(null);
    } catch (error) {
      console.error("Failed to rename thread:", error);
    }
  };

  // Content to show
  let content;
  if (isLoading) {
    content = (
      <div
        ref={ref}
        className={cn("text-sm text-muted-foreground p-2", className)}
        {...props}
      >
        Loading threads...
      </div>
    );
  } else if (error) {
    content = (
      <div
        ref={ref}
        className={cn(
          `text-sm text-destructive p-2 whitespace-nowrap ${isCollapsed ? "opacity-0 max-w-0 overflow-hidden" : "opacity-100"}`,
          className,
        )}
        {...props}
      >
        Error loading threads
      </div>
    );
  } else if (filteredThreads.length === 0) {
    content = (
      <div
        ref={ref}
        className={cn(
          `text-sm text-muted-foreground p-2 whitespace-nowrap ${isCollapsed ? "opacity-0 max-w-0 overflow-hidden" : "opacity-100"}`,
          className,
        )}
        {...props}
      >
        {searchQuery ? "No matching threads" : "No previous threads"}
      </div>
    );
  } else {
    content = (
      <div className="space-y-1">
        {filteredThreads.map((thread: TamboThread) => (
          <div
            key={thread.id}
            onClick={async () => await handleSwitchThread(thread.id)}
            className={cn(
              "p-2 rounded-md hover:bg-backdrop cursor-pointer group flex items-center justify-between",
              currentThread?.id === thread.id ? "bg-muted" : "",
              editingThread?.id === thread.id ? "bg-muted" : "",
            )}
          >
            <div className="text-sm flex-1">
              {editingThread?.id === thread.id ? (
                <form
                  onSubmit={handleNameSubmit}
                  className="flex flex-col gap-1"
                >
                  <input
                    ref={inputRef}
                    type="text"
                    value={newName}
                    onChange={(e) => setNewName(e.target.value)}
                    onKeyDown={handleKeyDown}
                    className="w-full bg-background px-1 text-sm font-medium focus:outline-none rounded-sm"
                    onClick={(e) => e.stopPropagation()}
                    placeholder="Thread name..."
                  />
                  <p className="text-xs text-muted-foreground truncate">
                    {new Date(thread.createdAt).toLocaleString(undefined, {
                      month: "short",
                      day: "numeric",
                      hour: "numeric",
                      minute: "2-digit",
                    })}
                  </p>
                </form>
              ) : (
                <>
                  <span className="font-medium line-clamp-1">
                    {thread.name ?? `Thread ${thread.id.substring(0, 8)}`}
                  </span>
                  <p className="text-xs text-muted-foreground truncate mt-1">
                    {new Date(thread.createdAt).toLocaleString(undefined, {
                      month: "short",
                      day: "numeric",
                      hour: "numeric",
                      minute: "2-digit",
                    })}
                  </p>
                </>
              )}
            </div>
            <ThreadOptionsDropdown
              thread={thread}
              onRename={handleRename}
              onGenerateName={handleGenerateName}
            />
          </div>
        ))}
      </div>
    );
  }

  return (
    <div
      ref={ref}
      className={cn(
        "overflow-y-auto flex-1 transition-all duration-300 ease-in-out",
        isCollapsed
          ? "opacity-0 max-h-0 overflow-hidden pointer-events-none"
          : "opacity-100 max-h-full pointer-events-auto",
        className,
      )}
      {...props}
    >
      {content}
    </div>
  );
});
ThreadHistoryList.displayName = "ThreadHistory.List";

/**
 * Dropdown menu component for thread actions
 */
const ThreadOptionsDropdown = ({
  thread,
  onRename,
  onGenerateName,
}: {
  thread: TamboThread;
  onRename: (thread: TamboThread) => void;
  onGenerateName: (thread: TamboThread) => void;
}) => {
  return (
    <DropdownMenu.Root>
      <DropdownMenu.Trigger asChild>
        <button
          className="p-1 hover:bg-backdrop rounded-md opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
          onClick={(e) => e.stopPropagation()}
        >
          <MoreHorizontal className="h-4 w-4 text-muted-foreground" />
        </button>
      </DropdownMenu.Trigger>
      <DropdownMenu.Portal>
        <DropdownMenu.Content
          className="min-w-[160px] text-xs bg-popover rounded-md p-1 shadow-md border border-border"
          sideOffset={5}
          align="end"
        >
          <DropdownMenu.Item
            className="flex items-center gap-2 px-2 py-1.5 text-foreground hover:bg-backdrop rounded-sm cursor-pointer outline-none transition-colors"
            onClick={(e) => {
              e.stopPropagation();
              onRename(thread);
            }}
          >
            <Pencil className="h-3 w-3" />
            Rename
          </DropdownMenu.Item>
          <DropdownMenu.Item
            className="flex items-center gap-2 px-2 py-1.5 text-foreground hover:bg-backdrop rounded-sm cursor-pointer outline-none transition-colors"
            onClick={(e) => {
              e.stopPropagation();
              onGenerateName(thread);
            }}
          >
            <Sparkles className="h-3 w-3" />
            Generate Name
          </DropdownMenu.Item>
        </DropdownMenu.Content>
      </DropdownMenu.Portal>
    </DropdownMenu.Root>
  );
};

export {
  ThreadHistory,
  ThreadHistoryHeader,
  ThreadHistoryList,
  ThreadHistoryNewButton,
  ThreadHistorySearch,
  ThreadOptionsDropdown,
};
